# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.fal.image_to_json
from nodetool.workflows.base_node import BaseNode

class BagelUnderstand(SingleOutputGraphNode[dict[str, Any]], GraphNode[dict[str, Any]]):
    """

        Bagel is a 7B parameter multimodal model from Bytedance-Seed that can generate both text and images.
        vision, analysis, json, image-understanding

        Use cases:
        - Image analysis to structured data
        - Visual content understanding
        - Automated image metadata extraction
        - Content classification
        - Image-based data extraction
    """

    prompt: str | OutputHandle[str] = connect_field(default='', description='The prompt to query the image with.')
    seed: int | OutputHandle[int] = connect_field(default=-1, description='The seed to use for the generation.')
    image: types.ImageRef | OutputHandle[types.ImageRef] = connect_field(default=types.ImageRef(type='image', uri='', asset_id=None, data=None, metadata=None), description='The image for the query.')

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.fal.image_to_json.BagelUnderstand

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


