# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.fal.video_to_text
from nodetool.workflows.base_node import BaseNode

class OpenrouterRouterVideo(SingleOutputGraphNode[dict[str, Any]], GraphNode[dict[str, Any]]):
    """

        Run any VLM (Video Language Model) with fal, powered by OpenRouter.
        video, transcription, analysis, video-understanding

        Use cases:
        - Video transcription
        - Video content analysis
        - Automated captioning
        - Video understanding
        - Content indexing
    """

    prompt: str | OutputHandle[str] = connect_field(default='', description='Prompt to be used for the video processing')
    videos: list[str] | OutputHandle[list[str]] = connect_field(default=[], description='List of URLs or data URIs of video files to process. Supported formats: mp4, mpeg, mov, webm. For Google Gemini on AI Studio, YouTube links are also supported. Mutually exclusive with video_url.')
    system_prompt: str | OutputHandle[str] = connect_field(default='', description='System prompt to provide context or instructions to the model')
    reasoning: bool | OutputHandle[bool] = connect_field(default=False, description='Should reasoning be the part of the final answer.')
    model: str | OutputHandle[str] = connect_field(default='', description='Name of the model to use. Charged based on actual token usage.')
    max_tokens: int | OutputHandle[int] = connect_field(default=0, description="This sets the upper limit for the number of tokens the model can generate in response. It won't produce more than this limit. The maximum value is the context length minus the prompt length.")
    temperature: float | OutputHandle[float] = connect_field(default=1, description="This setting influences the variety in the model's responses. Lower values lead to more predictable and typical responses, while higher values encourage more diverse and less common responses. At 0, the model always gives the same response for a given input.")

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.fal.video_to_text.OpenrouterRouterVideo

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.fal.video_to_text
from nodetool.workflows.base_node import BaseNode

class OpenrouterRouterVideoEnterprise(SingleOutputGraphNode[dict[str, Any]], GraphNode[dict[str, Any]]):
    """

        Run any VLM (Video Language Model) with fal, powered by OpenRouter.
        video, transcription, analysis, video-understanding

        Use cases:
        - Video transcription
        - Video content analysis
        - Automated captioning
        - Video understanding
        - Content indexing
    """

    prompt: str | OutputHandle[str] = connect_field(default='', description='Prompt to be used for the video processing')
    videos: list[str] | OutputHandle[list[str]] = connect_field(default=[], description='List of URLs or data URIs of video files to process. Supported formats: mp4, mpeg, mov, webm. For Google Gemini on AI Studio, YouTube links are also supported. Mutually exclusive with video_url.')
    system_prompt: str | OutputHandle[str] = connect_field(default='', description='System prompt to provide context or instructions to the model')
    reasoning: bool | OutputHandle[bool] = connect_field(default=False, description='Should reasoning be the part of the final answer.')
    model: str | OutputHandle[str] = connect_field(default='', description='Name of the model to use. Charged based on actual token usage.')
    max_tokens: int | OutputHandle[int] = connect_field(default=0, description="This sets the upper limit for the number of tokens the model can generate in response. It won't produce more than this limit. The maximum value is the context length minus the prompt length.")
    temperature: float | OutputHandle[float] = connect_field(default=1, description="This setting influences the variety in the model's responses. Lower values lead to more predictable and typical responses, while higher values encourage more diverse and less common responses. At 0, the model always gives the same response for a given input.")

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.fal.video_to_text.OpenrouterRouterVideoEnterprise

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


