import nodetool.nodes.fal.llm  # noqa: F401
import nodetool.nodes.fal.text_to_image  # noqa: F401
import nodetool.nodes.fal.text_to_audio  # noqa: F401
import nodetool.nodes.fal.speech_to_text  # noqa: F401
import nodetool.nodes.fal.image_to_image  # noqa: F401
import nodetool.nodes.fal.image_to_video  # noqa: F401
import nodetool.nodes.fal.text_to_video  # noqa: F401
import nodetool.nodes.fal.model3d  # noqa: F401
import nodetool.nodes.fal.dynamic_schema  # noqa: F401
